### PR TITLE
SubMaterial Fix

### PR DESCRIPTION
**Pull request by Etos7**
There is no continue in LUA.
SubMaterial index starts form 0.

### CODE REVIEW

**Comment by MalboroDEV** [comment]
Why did you change condition line 165?

**Comment by MalboroDEV** [comment]
WTF there is continue in LUA when you have a loop.

**Comment by Etos7** [comment]
Check the second commit.

`if type(k) != "number" or type(v) == "string" then continue end`
This IF statement will be alwys true and will exit for without doing:
`ent:SetSubMaterial( k-1, v )`
`v` will be alwys string.

**Comment by Etos7** [comment]
my bad there is continiue in **GLUA** but in **standard** LUA there is no continue
 http://lua-users.org/wiki/ContinueProposal
 https://stackoverflow.com/questions/3524970/why-does-lua-have-no-continue-statement/13825260
 http://lua-users.org/lists/lua-l/2006-12/msg00440.html

https://wiki.garrysmod.com/page/Specific_Operators

**Pull request merged**
